# Generated by Django 4.2.5 on 2023-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], max_length=12),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
