# Generated by Django 4.2.5 on 2023-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animei', '0002_alter_anime_id_alter_anime_status_alter_episode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('IN PROGRESS', 'In Progress')], max_length=12),
        ),
    ]
