# Generated by Django 4.2.5 on 2023-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animei', '0003_alter_anime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], max_length=12),
        ),
    ]
